# Generated by Django 4.1.6 on 2023-02-09 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='New_Bikes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=40)),
                ('model', models.CharField(max_length=40)),
                ('sex_age', models.CharField(max_length=10)),
                ('veloformat', models.CharField(max_length=7)),
                ('picture', models.ImageField(upload_to='')),
                ('price', models.FloatField()),
            ],
        ),
    ]
