# Generated by Django 4.1.6 on 2023-02-09 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikes', '0002_sportsmens'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new_bikes',
            name='picture',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='new_bikes',
            name='veloformat',
            field=models.CharField(max_length=15),
        ),
    ]
