# Generated by Django 4.1.6 on 2023-02-13 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikes', '0003_alter_new_bikes_picture_alter_new_bikes_veloformat'),
    ]

    operations = [
        migrations.AddField(
            model_name='new_bikes',
            name='add_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
