# Generated by Django 4.1.6 on 2023-02-13 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikes', '0004_new_bikes_add_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='new_bikes',
            name='description',
            field=models.TextField(default='Велосипед для катания'),
        ),
    ]
