# Generated by Django 4.1.6 on 2023-02-15 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikes', '0007_rename_new_bikes_new_bike'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='new_bike',
            options={'verbose_name': 'Велосипед', 'verbose_name_plural': 'Велосипеды'},
        ),
        migrations.AlterField(
            model_name='new_bike',
            name='add_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата добавления в БД'),
        ),
        migrations.AlterField(
            model_name='new_bike',
            name='brand',
            field=models.CharField(max_length=40, verbose_name='Производитель'),
        ),
        migrations.AlterField(
            model_name='new_bike',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='new_bike',
            name='model',
            field=models.CharField(max_length=40, verbose_name='Модель'),
        ),
        migrations.AlterField(
            model_name='new_bike',
            name='picture',
            field=models.TextField(verbose_name='Изображение товара'),
        ),
        migrations.AlterField(
            model_name='new_bike',
            name='price',
            field=models.FloatField(verbose_name='Стоимость'),
        ),
        migrations.AlterField(
            model_name='new_bike',
            name='sex_age',
            field=models.CharField(default='Взрослый', max_length=10, verbose_name='Пол и возраст'),
        ),
    ]
