# Generated by Django 4.1.6 on 2023-02-15 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikes', '0008_alter_new_bike_options_alter_new_bike_add_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='new_bike',
            name='reliability',
            field=models.FloatField(blank=True, default=0, verbose_name='Кол-во поломок на 100 шт.'),
        ),
        migrations.AlterField(
            model_name='new_bike',
            name='veloformat',
            field=models.CharField(default='Горный', max_length=15, verbose_name='Формат'),
        ),
    ]
