# Generated by Django 4.1.6 on 2023-02-17 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikes', '0010_alter_new_bike_reliability'),
    ]

    operations = [
        migrations.AddField(
            model_name='new_bike',
            name='wheel_count',
            field=models.CharField(choices=[('UNI', 'Уницикл'), ('BI', 'Обычный'), ('TRI', 'Трицикл'), ('OTH', 'Другое')], default='BI', max_length=3, verbose_name='Количество колес'),
        ),
        migrations.AlterField(
            model_name='new_bike',
            name='veloformat',
            field=models.CharField(default='Горный', max_length=15, verbose_name='Назначение'),
        ),
    ]
