# Generated by Django 4.1.6 on 2023-02-18 19:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikes', '0012_alter_new_bike_wheel_count'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sportsmens',
            options={'verbose_name': 'Спортсмен', 'verbose_name_plural': 'Спортсмены'},
        ),
        migrations.RemoveField(
            model_name='sportsmens',
            name='distance',
        ),
        migrations.AddField(
            model_name='sportsmens',
            name='all_distance',
            field=models.IntegerField(default=100, verbose_name='Пройденная за карьеру дистанция'),
        ),
        migrations.AddField(
            model_name='sportsmens',
            name='brand_distance',
            field=models.IntegerField(default=100, verbose_name='Пройденная дистанция за брэнд'),
        ),
        migrations.AddField(
            model_name='sportsmens',
            name='count_trophy',
            field=models.IntegerField(default=0, verbose_name='Количество наград'),
        ),
        migrations.AlterField(
            model_name='new_bike',
            name='price',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Стоимость'),
        ),
        migrations.AlterField(
            model_name='new_bike',
            name='reliability',
            field=models.IntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Поломок на 100 шт.'),
        ),
        migrations.AlterField(
            model_name='sportsmens',
            name='birthday',
            field=models.DateField(verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='sportsmens',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='sportsmens',
            name='surname',
            field=models.CharField(max_length=50, verbose_name='Фамилия'),
        ),
    ]
