# Generated by Django 4.1.6 on 2023-02-18 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikes', '0013_alter_sportsmens_options_remove_sportsmens_distance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sportsmens',
            name='all_distance',
            field=models.IntegerField(verbose_name='Пройденная за карьеру дистанция'),
        ),
        migrations.AlterField(
            model_name='sportsmens',
            name='brand_distance',
            field=models.IntegerField(verbose_name='Пройденная дистанция за брэнд'),
        ),
        migrations.AlterField(
            model_name='sportsmens',
            name='count_trophy',
            field=models.IntegerField(blank=True, verbose_name='Количество наград'),
        ),
    ]
