# Generated by Django 4.1.6 on 2023-02-18 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikes', '0015_alter_sportsmens_count_trophy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sportsmens',
            name='count_trophy',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Количество наград'),
        ),
    ]
