# Generated by Django 4.1.6 on 2023-02-18 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bikes', '0018_alter_sportsmens_sex'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sportsmens',
            new_name='Sportsman',
        ),
        migrations.AddField(
            model_name='new_bike',
            name='sportsman',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='bikes.sportsman'),
        ),
    ]
