# Generated by Django 4.1.6 on 2023-02-19 05:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bikes', '0019_rename_sportsmens_sportsman_new_bike_sportsman'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new_bike',
            name='sportsman',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='bikes.sportsman'),
        ),
        migrations.AlterField(
            model_name='new_bike',
            name='wheel_count',
            field=models.CharField(default='BI', max_length=3, verbose_name='Кол-во колес'),
        ),
        migrations.AlterField(
            model_name='sportsman',
            name='sex',
            field=models.CharField(choices=[('MAN', 'Мужчина'), ('WOMAN', 'Женщина')], max_length=5, verbose_name='Пол'),
        ),
    ]
