# Generated by Django 4.1.6 on 2023-02-19 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bikes', '0020_alter_new_bike_sportsman_alter_new_bike_wheel_count_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Extension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extension', models.CharField(max_length=40, verbose_name='Расширение для велосипеда')),
                ('brand_extension', models.CharField(max_length=40, verbose_name='Производитель')),
                ('description', models.TextField(verbose_name='Описание расширения')),
            ],
        ),
        migrations.AlterField(
            model_name='new_bike',
            name='sportsman',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bikes.sportsman'),
        ),
        migrations.AlterField(
            model_name='sportsman',
            name='sex',
            field=models.CharField(choices=[('MAN', 'Мужчина'), ('WOMAN', 'Женщина')], max_length=7, verbose_name='Пол'),
        ),
        migrations.AddField(
            model_name='new_bike',
            name='extensions',
            field=models.ManyToManyField(to='bikes.extension'),
        ),
    ]
