# Generated by Django 4.1.6 on 2023-02-19 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikes', '0021_extension_alter_new_bike_sportsman_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extension',
            name='extension',
            field=models.CharField(max_length=80, verbose_name='Расширение для велосипеда'),
        ),
    ]
