# Generated by Django 4.1.6 on 2023-02-20 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikes', '0024_alter_new_bike_wheel_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='new_bike',
            name='brand_slug',
            field=models.SlugField(default='', verbose_name='Slug Брэнда'),
        ),
        migrations.AddField(
            model_name='new_bike',
            name='model_slug',
            field=models.SlugField(default='', verbose_name='Slug Модели'),
        ),
    ]
