# Generated by Django 4.1.6 on 2023-02-20 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikes', '0025_new_bike_brand_slug_new_bike_model_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new_bike',
            name='brand_slug',
            field=models.SlugField(verbose_name='Slug Брэнда'),
        ),
    ]
