# Generated by Django 4.1.6 on 2023-02-20 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikes', '0026_alter_new_bike_brand_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new_bike',
            name='add_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления в БД'),
        ),
        migrations.AlterField(
            model_name='new_bike',
            name='model_slug',
            field=models.SlugField(unique=True, verbose_name='Slug Модели'),
        ),
    ]
