# Generated by Django 4.1.6 on 2023-02-20 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikes', '0028_alter_new_bike_brand_slug_alter_new_bike_model_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new_bike',
            name='model',
            field=models.CharField(max_length=50, verbose_name='Модель'),
        ),
    ]
