# Generated by Django 4.1.6 on 2023-02-21 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikes', '0034_alter_new_bike_sex_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new_bike',
            name='sex_age',
            field=models.CharField(choices=[('MAN-ADULT', 'man-adult'), ('MAN-CHILD', 'man-child'), ('WOMAN-ADULT', 'woman-adult'), ('WOMAN-CHILD', 'woman-child')], default='Взрослый/мужской', max_length=16, verbose_name='Пол и возраст'),
        ),
    ]
