# Generated by Django 4.1.6 on 2023-02-21 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikes', '0037_alter_new_bike_sex_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new_bike',
            name='sex_age',
            field=models.CharField(choices=[('Man-Adult', 'Man-Adult'), ('Man-Child', 'Man-Child'), ('Woman-Adult', 'Woman-Adult'), ('Woman-Child', 'Woman-Child')], default='Взрослый/мужской', max_length=16, verbose_name='Пол и возраст'),
        ),
    ]
