# Generated by Django 4.1.6 on 2023-02-21 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikes', '0039_alter_new_bike_sex_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new_bike',
            name='sex_age',
            field=models.CharField(choices=[('M', 'M'), ('MC', 'MC'), ('W', 'W'), ('WC', 'WC')], default='Взрослый/мужской', max_length=16, verbose_name='Пол и возраст'),
        ),
    ]
