# Generated by Django 4.1.6 on 2023-02-22 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikes', '0040_alter_new_bike_sex_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new_bike',
            name='sex_age',
            field=models.CharField(choices=[('m', 'M'), ('mc', 'MC'), ('w', 'W'), ('wc', 'WC')], default='Взрослый/мужской', max_length=16, verbose_name='Пол и возраст'),
        ),
        migrations.AlterField(
            model_name='new_bike',
            name='veloformat',
            field=models.CharField(default='Mountain', max_length=15, verbose_name='Назначение'),
        ),
    ]
