# Generated by Django 4.1.6 on 2023-02-22 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikes', '0041_alter_new_bike_sex_age_alter_new_bike_veloformat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new_bike',
            name='veloformat',
            field=models.CharField(default='mountain', max_length=15, verbose_name='Назначение'),
        ),
    ]
