# Generated by Django 4.1.6 on 2023-02-22 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikes', '0042_alter_new_bike_veloformat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new_bike',
            name='sex_age',
            field=models.CharField(choices=[('Мужской взрослый', 'M'), ('Мужской детский', 'MC'), ('w', 'W'), ('wc', 'WC')], default='Взрослый/мужской', max_length=16, verbose_name='Пол и возраст'),
        ),
    ]
