# Generated by Django 4.1.6 on 2023-02-22 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikes', '0043_alter_new_bike_sex_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new_bike',
            name='sex_age',
            field=models.CharField(choices=[('Мужской взрослый', 'ManAd'), ('Мужской детский', 'ManCh'), ('Женский взрослый', 'WomanAd'), ('Женский детский', 'WomanCh')], max_length=16, verbose_name='Пол и возраст'),
        ),
    ]
