# Generated by Django 4.1.6 on 2023-02-22 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikes', '0044_alter_new_bike_sex_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new_bike',
            name='sex_age',
            field=models.CharField(choices=[('Man', 'ManAd'), ('Boy', 'ManCh'), ('Woman', 'WomanAd'), ('Girl', 'WomanCh')], max_length=16, verbose_name='Пол и возраст'),
        ),
    ]
