# Generated by Django 4.1.6 on 2023-03-05 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bikes', '0046_alter_new_bike_sex_age'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='extension',
            options={'verbose_name': 'Расширение', 'verbose_name_plural': 'Расширения'},
        ),
    ]
