# Generated by Django 4.1.6 on 2023-04-03 10:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikes', '0048_alter_new_bike_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new_bike',
            name='price',
            field=models.FloatField(default=30000, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000000)], verbose_name='Стоимость'),
        ),
    ]
