# Generated by Django 4.1.6 on 2023-03-05 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedback',
            options={'ordering': ('-pub_date',), 'verbose_name': 'Отзыв', 'verbose_name_plural': 'Отзывы'},
        ),
        migrations.AlterField(
            model_name='feedback',
            name='text',
            field=models.TextField(help_text='Напишите простой и понятный отзыв', max_length=1000, verbose_name='Текст отзыва'),
        ),
    ]
